/* global React, Switch */
const ProfileScreen=({data,theme,onThemeToggle,accent,onAccentChange,onLogout,lang,setLang,fontSize,setFontSize,notifications,setNotifications,security,setSecurity,credentials,setCredentials,onBack})=>{
  const tr=(zh,en)=>lang==='zh'?zh:en,[securityOpen,setSecurityOpen]=React.useState(false),states=data.devicesState||{};
  const devices=[['mppt-001',tr('MPPT 能源','MPPT Energy')],['esp32-001',tr('环境与圆顶','Environment & Roof')],['ef-001',tr('电动平场板','Flat Field Panel')]];
  const runtime=s=>Number(s?.telemetry?.runtime_seconds??s?.telemetry?.uptime??s?.telemetry?.uptime_seconds),fmtRuntime=s=>Number.isFinite(s)&&s>0?`${Math.floor(s/86400)}d ${Math.floor(s%86400/3600)}h`:'--';
  const setNotice=(key,value)=>setNotifications({...notifications,[key]:value});
  return <div className="page-enter account-console">
    <AccountTop title={tr('个人中心','Profile')} subtitle={tr('账户 · 设备 · 偏好','Account · Devices · Preferences')} onBack={onBack} lang={lang} setLang={setLang}/>
    <main className="account-content">
      <section className="account-hero glass-card"><div className="account-avatar">羊</div><div><small>REMOTE OBSERVATORY OPERATOR</small><h1>{tr('天文台管理员','Observatory Administrator')}</h1><p>{credentials.user} · astro@observatory.local</p></div><div className="account-badges"><span>ADMIN</span><span>{devices.filter(([id])=>states[id]?.online).length}/3 {tr('在线','ONLINE')}</span></div></section>

      <section className="runtime-section"><header><h2>{tr('设备运行与连接','Device Runtime & Connectivity')}</h2><span>{tr('实时状态来自 MQTT','Live status from MQTT')}</span></header><div className="runtime-grid">{devices.map(([id,name])=>{const s=states[id]||{},online=Boolean(s.online);return <article className={`runtime-card glass-card ${online?'online':''}`} key={id}><header><span><i/>{online?tr('在线','Online'):tr('离线','Offline')}</span><small>{id}</small></header><h3>{name}</h3><div className="runtime-value">{fmtRuntime(runtime(s))}<small>{tr('设备运行时长','Device Runtime')}</small></div><footer><span>{online?tr('最近上线','Last Online'):tr('最近离线','Last Offline')}</span><time>{s.lastSeen?new Date(s.lastSeen).toLocaleString(lang==='zh'?'zh-CN':'en-US'):'--'}</time></footer></article>})}</div></section>

      <section className="connection-card glass-card"><header><div><h2>{tr('上下线历史','Connectivity History')}</h2><small>{tr('最近 24 小时状态事件','Status events in the last 24 hours')}</small></div><div className="connection-legend">{devices.map(([id,name],i)=><span key={id}><i style={{background:['#4fd18b','#55a7ff','#f1b35c'][i]}}/>{name}</span>)}</div></header><ConnectionHistory states={states} logs={data.logs||[]} devices={devices}/></section>

      <section className="preference-grid">
        <article className="preference-card glass-card"><header><h2>{tr('外观与显示','Appearance & Display')}</h2></header><PreferenceRow label={tr('外观','Theme')} desc={tr('完整切换界面明暗配色','Switch all interface surfaces')}><Segmented options={[["dark",tr('深色','Dark')],["light",tr('浅色','Light')]]} value={theme} set={onThemeToggle}/></PreferenceRow><PreferenceRow label={tr('主题色','Accent Color')} desc={tr('按钮、状态与高亮；历史曲线保持固定配色','Controls, status and highlights; history charts keep fixed colors')}><div className="accent-options">{[['#27E58A','green'],['#4FB6FF','blue'],['#A78BFA','violet'],['#F59E0B','amber'],['#EC4899','rose']].map(([c,name])=><button key={c} aria-label={name} className={accent===c?'active':''} style={{'--swatch':c}} onClick={()=>onAccentChange(c)}/>)}</div></PreferenceRow><PreferenceRow label={tr('语言','Language')} desc={tr('大屏、设置与登录界面','Dashboard, settings and login')}><Segmented options={[["zh","中文"],["en","English"]]} value={lang} set={setLang}/></PreferenceRow><PreferenceRow label={tr('字体大小','Font Size')} desc={tr('缩小、标准或放大所有界面','Scale the complete interface')}><Segmented options={[["small",tr('小','Small')],["normal",tr('标准','Normal')],["large",tr('大','Large')]]} value={fontSize} set={setFontSize}/></PreferenceRow></article>

        <article className="preference-card glass-card"><header><h2>{tr('通知开关','Notification Channels')}</h2></header><TogglePreference label={tr('设备掉线','Device Offline')} desc={tr('任意 ESP32 失联时通知','Notify when an ESP32 disconnects')} value={notifications.deviceOffline} set={v=>setNotice('deviceOffline',v)}/><TogglePreference label={tr('雨水告警','Rain Alert')} desc={tr('雨水传感器触发时通知','Notify when rain is detected')} value={notifications.rainAlert} set={v=>setNotice('rainAlert',v)}/><TogglePreference label={tr('拍摄结束手机通知','Capture Complete Push')} desc={tr('观测任务完成后发送手机推送','Send mobile push after capture')} value={notifications.capturePush} set={v=>setNotice('capturePush',v)}/><TogglePreference label={tr('邮箱通知','Email Notification')} desc={tr('向账户邮箱发送告警摘要','Send alert summaries by email')} value={notifications.email} set={v=>setNotice('email',v)}/></article>
      </section>

      <section className="account-actions glass-card"><div><h2>{tr('账号安全','Account Security')}</h2><p>{tr('修改密码与登录设备管理','Password and signed-in device management')}</p></div><button onClick={()=>setSecurityOpen(true)}>{tr('管理账号安全','Manage Security')}</button><button className="logout" onClick={onLogout}>{tr('退出登录','Sign Out')}</button></section>
    </main>
    {securityOpen&&<SecurityModal close={()=>setSecurityOpen(false)} lang={lang} credentials={credentials} setCredentials={setCredentials} security={security} setSecurity={setSecurity}/>}
  </div>;
};
const AccountTop=({title,subtitle,onBack,lang,setLang})=><header className="account-topbar"><button onClick={onBack}>←</button><div><small>REMOTE OBSERVATORY</small><h1>{title}<span>{subtitle}</span></h1></div><div><button onClick={()=>setLang(lang==='zh'?'en':'zh')}>{lang==='zh'?'EN':'中文'}</button><b>羊</b></div></header>;
const PreferenceRow=({label,desc,children})=><div className="preference-row"><div><b>{label}</b><small>{desc}</small></div>{children}</div>;
const TogglePreference=({label,desc,value,set})=><PreferenceRow label={label} desc={desc}><Switch on={value} onChange={set}/></PreferenceRow>;
const Segmented=({options,value,set})=><div className="profile-segmented">{options.map(([v,l])=><button className={value===v?'on':''} key={v} onClick={()=>set(v)}>{l}</button>)}</div>;
const ConnectionHistory=({states,logs,devices})=>{const w=900,h=142,pL=50,pR=12,pT=12,pB=24,colors=['#4fd18b','#55a7ff','#f1b35c'];return <svg className="connection-chart" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none">{devices.map((_,i)=><line className="lane" key={i} x1={pL} y1={30+i*36} x2={w-pR} y2={30+i*36}/>)}{devices.map(([id],i)=>{const online=states[id]?.online,y=30+i*36,events=(logs||[]).filter(l=>String(l.msg).includes(id)&&String(l.msg).includes('/status')).slice(0,12).reverse();const pts=events.length>1?events.map((e,j)=>[pL+j*(w-pL-pR)/(events.length-1),y+(String(e.msg).includes('offline')?8:-8)]):[[pL,y+(online?-8:8)],[w-pR,y+(online?-8:8)]];return <path key={id} d={pts.map((p,j)=>`${j?'L':'M'}${p[0]},${p[1]}`).join(' ')} style={{stroke:colors[i]}}/>})}{['24h','18h','12h','6h','Now'].map((x,i)=><text key={x} x={pL+i*(w-pL-pR)/4} y={h-5} textAnchor={i===0?'start':i===4?'end':'middle'}>{x}</text>)}</svg>};
const SecurityModal=({close,lang,credentials,setCredentials,security,setSecurity})=>{const tr=(zh,en)=>lang==='zh'?zh:en,[current,setCurrent]=React.useState(''),[next,setNext]=React.useState(''),[confirm,setConfirm]=React.useState(''),[message,setMessage]=React.useState(null);const save=e=>{e.preventDefault();if(current!==credentials.password)return setMessage({ok:false,text:tr('当前密码不正确','Current password is incorrect')});if(next.length<8)return setMessage({ok:false,text:tr('新密码至少 8 位','New password must be at least 8 characters')});if(next!==confirm)return setMessage({ok:false,text:tr('两次密码不一致','Passwords do not match')});setCredentials({...credentials,password:next});setCurrent('');setNext('');setConfirm('');setMessage({ok:true,text:tr('密码已更新，下次登录生效','Password updated for the next sign-in')})};return <div className="profile-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="security-modal glass-card" role="dialog" aria-label={tr('账号安全','Account Security')}><header><h2>{tr('账号安全','Account Security')}</h2><button onClick={close}>×</button></header><div className="security-content"><form onSubmit={save}><h3>{tr('修改密码','Change Password')}</h3><label>{tr('当前密码','Current Password')}<input type="password" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>{tr('新密码','New Password')}<input type="password" value={next} onChange={e=>setNext(e.target.value)}/></label><label>{tr('确认新密码','Confirm Password')}<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{message&&<p className={message.ok?'ok':'error'}>{message.text}</p>}<button type="submit">{tr('保存新密码','Save Password')}</button></form><section><h3>{tr('登录设备','Signed-in Devices')}</h3><div className="session-row"><div><b>Windows · Codex</b><small>{tr('当前会话 · 中国上海','Current session · Shanghai, CN')}</small></div><span>{tr('当前','Current')}</span></div>{security.otherSessions&&<div className="session-row"><div><b>Chrome · Linux Server</b><small>{tr('最近活动 2 天前','Last active 2 days ago')}</small></div><button onClick={()=>setSecurity({...security,otherSessions:false})}>{tr('撤销','Revoke')}</button></div>}<button className="revoke-all" disabled={!security.otherSessions} onClick={()=>setSecurity({...security,otherSessions:false})}>{tr('退出其他设备','Sign out other devices')}</button></section></div></section></div>};
window.ProfileScreen=ProfileScreen;
