persistence true
persistence_location /mosquitto/data/
log_dest stdout
sys_interval 5
allow_anonymous false
password_file /mosquitto/dynamic-config/passwd
acl_file /mosquitto/dynamic-config/acl.conf
listener 1883 127.0.0.1
protocol mqtt
listener 9001 127.0.0.1
protocol websockets
socket_domain ipv4
max_packet_size 69632
max_queued_messages 1000
max_inflight_messages 20
max_connections 100
